function [dmdt] = Dmdt(m , time)

m_x = m(1);
m_y = m(2);
m_z = m(3);

global f ...
    B_x  ...
    B_y  ...
    B_z  ...
    N_x  ...
    N_y  ...
    N_z  ...
    mu_0 ...
    M_s  ...
    gamma...
    sigma...
    y    ...
    alpha...    
    B_Oe ...
    B_FL ...
    B_DL ;

B_ext = [B_x ; B_y ; B_z];
B_demag = -mu_0 * M_s * [N_x * m_x ; N_y * m_y ; N_z * m_z];
B_eff = B_ext + B_demag - B_Oe * cos(2 * pi * f * time) * y + B_FL * cos(2 * pi * f * time) * sigma;

A = eye(3) - alpha * cross2mat(m);

b = -gamma * cross(m , B_eff) + gamma * B_DL * cross(m , cross(sigma , m)) * cos(2 * pi * f * time);

dmdt = A^-1 * b;

% dmdt = gamma / (1 + alpha^2) * (-cross(m , B_eff)...
%     -alpha * dot(m , B_eff) * m...
%     +alpha * B_eff...
%     +B_DL * cos(2 * pi * f * time) * (alpha * cross(m , sigma) + sigma - dot(m , sigma) * m));

end